### ISSUE TITLE
Buffers "GET" method is not a function

### ISSUE THREAD

**Issue by Tomino2112** [drewblaisdell/monitor.io#3]
Hi, getting this error:

```
Tue, 23 Aug 2016 13:39:50 GMT uncaughtException: this.buffers[pos.buf].get is not a function
TypeError: this.buffers[pos.buf].get is not a function
    at Buffers.get (node_modules/buffers/index.js:185:34)
    at parse (node_modules/telnet/lib/telnet.js:145:15)
    at Socket.<anonymous> (node_modules/telnet/lib/telnet.js:201:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

**Comment by frey1esm** [comment]
+1

**Comment by pupca** [comment]
+1

**Comment by AlexanderSchroeder** [comment]
+1

**Comment by AilisObrian** [comment]
happened to me when I used this with

```
node: 6.5.0
express: 4.14.0
socket.io: 1.5.0
monitor.io: 0.1.0
```

**Comment by DanielSmith** [comment]
+1

**Comment by seefeld** [comment]
+1

**Comment by gwjjeff** [comment]
+1

**Comment by abeloeil** [comment]
Did you find any solution?

**Comment by rubikcuber** [comment]
This is an issue in dependency node-buffers (which looks like it's no longer maintained). See https://github.com/substack/node-buffers/issues/16

**Comment by okayawright** [comment]
+1

**Comment by codekraft-studio** [comment]
basically is no more working cause of this.. is this repo still maintained?
After fixing as @rubikcuber suggested, it's working but in a strange way, it doesn't render correctly the interface and it does a lot of: 
`Fatal error: Cannot read property 'toString' of undefined`
when using it :(

**Comment by jjzlaw** [comment]
+1

**Comment by ka1** [comment]
+1

**Comment by b4dnewz** [comment]
if someone is interested I made **monitor.io** working again (still buggy sometimes and still work in progress) by using another module (referenced above) called terminal-kit, here is the [link of the fork](https://github.com/b4dnewz/monitor.io).

I made this because I never had a chance to use the original one and looks cool and useful.

**Comment by pak11273** [comment]
@b4dnewz I cloned your fork and tried it out.  I get a backbone error: this.get is not a function.

**Comment by b4dnewz** [comment]
> I get a backbone error: this.get is not a function.

Hi @pak11273, I've checked and you are right, the version I was referring when I posted it wasn't working on remote mode but only in local mode.. but this error It shouldn't appear since I changed the main dependency, are you sure you was trying with the fork version?

I've enabled the [issues](https://github.com/b4dnewz/monitor.io/issues) on the repository so if you are interested on the project, feel free to open there any question or bug.

I've pushed some changes right now that I forgot to commit and push last month when I spent some time on it. 

Now it should work in local mode in a pretty decent way but not in the remote mode, at least, I'm not sure if is working on all OS, pretty sure is not working with windows systems, but I will try to fix it when I've some time.

I would like to complete 100% this project and make it working again but is quite complicate and takes me a long time (that right now I don't have) but I will keep coding on it once in a while.

**Comment by pak11273** [comment]
I'll raise the issue on your repo.  thanks!

**Comment by DriftN2Forty** [comment]
+1

**Comment by Mello21century** [comment]
+1

**Comment by DriftN2Forty** [comment]
You can get the code semi working using this fix for buffers https://github.com/substack/node-buffers/issues/16

in index.js 185 we should use:
return this.buffers[pos.buf][pos.offset];
instead of:
return this.buffers[pos.buf].get(pos.offset);
